# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"
      - "docs"

jobs:
  publish-docs:
    name: "Publish docs"
    uses: "phpDocumentor/.github/.github/workflows/docs.yml@main"
